package Parsing;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 4;
  public static final int MENOR = 18;
  public static final int CP = 11;
  public static final int IGUAL = 19;
  public static final int OR = 5;
  public static final int MAYEQ = 16;
  public static final int DESIGUAL = 20;
  public static final int NOT = 6;
  public static final int TRUE = 2;
  public static final int IMPLIES = 9;
  public static final int CC = 13;
  public static final int AP = 10;
  public static final int NUM = 21;
  public static final int CHARTEXT = 22;
  public static final int COMA = 14;
  public static final int EVENTUALLY_ = 7;
  public static final int MAYOR = 15;
  public static final int EOF = 0;
  public static final int MENEQ = 17;
  public static final int FALSE = 3;
  public static final int AC = 12;
  public static final int error = 1;
  public static final int ALWAYS_ = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TRUE",
  "FALSE",
  "AND",
  "OR",
  "NOT",
  "EVENTUALLY_",
  "ALWAYS_",
  "IMPLIES",
  "AP",
  "CP",
  "AC",
  "CC",
  "COMA",
  "MAYOR",
  "MAYEQ",
  "MENEQ",
  "MENOR",
  "IGUAL",
  "DESIGUAL",
  "NUM",
  "CHARTEXT"
  };
}

